force-app/main/default/objects/Session_Details__c/Session_Details__c.object-meta.xml
<CustomObject>
    <label>Session Details</label>
    <nameField>
        <displayFormat>SD-{00}</displayFormat>
        <label>Session Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Details__c/fields/Sessions__c.field-meta.xml
<CustomField>
    <fullName>Sessions__c</fullName>
    <label>Sessions</label>
    <referenceTo>Sessions__c</referenceTo>
    <relationshipLabel>Session Details</relationshipLabel>
    <relationshipName>Session_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sessions__c/Sessions__c.object-meta.xml
<CustomObject>
    <label>Sessions</label>
    <nameField>
        <label>Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SessionDetailsController.cls
public with sharing class SessionDetailsController {
    public SessionDetailsController() {

    }

    @AuraEnabled(cacheable=true)
    public static list<Session_Details__c> getSessionDetails(String searchKey){
        List<Session_Details__c> sessionDetailsResults = new List<Session_Details__c>();
        try {
            
            System.debug(LoggingLevel.DEBUG, '---> search param ' + searchKey);

            sessionDetailsResults = [SELECT Id, Name, Capacity__c, Manufacturer__c, Sessions__c
                                                    FROM Session_Details__c
                                                    WHERE Sessions__c = :searchKey];
            if(sessionDetailsResults.isEmpty()) {
                throw new AuraHandledException('Session Details not found, try a new session ...');
            }
            return sessionDetailsResults;
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'Error : ' + ex.getMessage());
            return sessionDetailsResults;
        }
    }        
}