force-app/main/default/objects/Custom_Location__c/Custom_Location__c.object-meta.xml
<CustomObject>
    <label>Custom Location</label>
    <nameField>
        <displayFormat>CL-{00}</displayFormat>
        <label>Custom Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sessions__c/Sessions__c.object-meta.xml
<CustomObject>
    <label>Sessions</label>
    <nameField>
        <label>Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sessions__c/fields/Custom_Location__c.field-meta.xml
<CustomField>
    <fullName>Custom_Location__c</fullName>
    <label>Custom Location</label>
    <referenceTo>Custom_Location__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionsController.cls
public with sharing class SessionsController {
    public SessionsController() {

    }
    @AuraEnabled(cacheable=true)
    public static list<Sessions__c> getSessions(String searchKey){
        List<Sessions__c> sessionResults = new List<Sessions__c>();
        try {
            sessionResults = [SELECT Id, Name, Custom_Location__c, Session_Name__c
                                                    FROM Sessions__c
                                                    WHERE Custom_Location__c = :searchKey];
            if(sessionResults.isEmpty()) {
                throw new AuraHandledException('Sessions not found, try a new location ...');
            }
            return sessionResults;
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, 'Error : ' + ex.getMessage());
            return sessionResults;
        }
    }    

}